### ISSUE TITLE
302 Redirects Currently being used to redirect toward language URL

### ISSUE THREAD

**Issue by junseth** [sunnankar/wuc#1]
Currently, if you go to http://www.weusecoins.com/, you will be 302 redirected to http://www.weusecoins.com/en/. This redirect tells google that the permanent page hasn't moved and is still at http://www.weusecoins.com/ even though no one ever goes to this page because it is nothing more than a redirect to your language. Change these redirects sitewide to be 301 which will indicate to google that it is a sitewide change.

**Comment by sunnankar** [comment]
@junseth I think this issue has been cleared up. Now it might be good to use canonical tags to help Google out. Also going to need to do some updating on the other language URLs. All over in the new repo: https://github.com/sunnankar/wuc-new/issues
