### ISSUE TITLE
Sitewide redirects for language are done by region

### ISSUE THREAD

**Issue by junseth** [sunnankar/wuc#2]
This is probably a bad method for directing users who coem to the site largely through organic search. We should probably pick one language to focus on (I would say en-us), and make that the default first page if someone comes to the base domain. Then, we can give them the choice. I will add geo-cues to Google in webmaster tools so that G can know which content to deliver in search.

**Comment by sunnankar** [comment]
@junseth I think the new implementation does this. The alternate languages are in the footer. I also found all the subtitles (22 total) for the video and uploaded them to the Materials page and to Youtube for CC. Moving things forward in the new repo. https://github.com/sunnankar/wuc-new/issues
