### ISSUE TITLE
Remove META keywords sitewide

### ISSUE THREAD

**Issue by junseth** [sunnankar/wuc#4]
<meta name="keywords" content="bitcoin, what is bitcoin, best bitcoin wallet, best bitcoin exchange, buy bitcoin, virtual currency, digital currency">
Remove the keywords meta tag from the site. These are no longer used for ranking, and there is no reason to put them in the header.

**Comment by sunnankar** [comment]
Let's move over to the new repo. https://github.com/sunnankar/wuc-new/issues
