### ISSUE TITLE
301, 404d pages.

### ISSUE THREAD

**Issue by junseth** [sunnankar/wuc#5]
Something changed on Mar. 28th. Here is a list of the pages that were affected by the change. This list should be 301d to new pages or the pages themselves fixed. https://docs.google.com/spreadsheets/d/1NeUzglIRevGrUZLwp87sM_pVi-IBoIg2H41FnxkfmFw/edit?usp=sharing

**Comment by sunnankar** [comment]
@junseth I got everything moved over to the https://github.com/sunnankar/wuc-new/issues repo and tried to take care of most of the 404s that Google and a broken link checker could find. Perhaps we can move the issues and discussions with comments over there also.
